#
# This file is part of THM Addons — https://github.com/Leonn170709/THM-Addons
# Copyright (c) THM Addons contributors. Credit the devs, keep the link.
# By using this code you agree to the license terms and to keep your repo public.
#

[versions]
mod-version = "0.2.11"

# Fabric (https://fabricmc.net/develop)
jdk = "25"
fabric-loader = "0.19.3"

# Loom (https://github.com/FabricMC/fabric-loom)
loom = "1.17-SNAPSHOT"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
